name: Deploy GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (si necesitas builds)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'

  deploy:
    runs-on: ubuntu-latest
    needs: build-deploy
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with: {}
